version: 2.1
jobs:
  build:
    working_directory: ~/transenvios-shipping-web
    docker:
      - image: cimg/node:18.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          key: transenvios-shipping-web-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: "Install packages"
          command: "npm install"
      - save_cache:
          key: transenvios-shipping-web-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

workflows:
  build-app:
    jobs:
      - build
